# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: rootbeet

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: rootbeet
    salt: "rootbeet"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  trellis.wp-dev.space:
    env:
      db_password: rootbeet
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "pxjef:IZ;]K|m`f7g,R_HYTxfJt4k0$KqLKj?^PKeqE-fGTRQ7R9zL]9zCa9F[{F"
      secure_auth_key: "Xtn![(:(/{NP>!c!S=}hK)mE;=-NVamZ@0/Hab@|#U@6}ow6!Yl)Utf;{Aj{]wa_"
      logged_in_key: "7#Sc]?whzV0O[0]g`usSUT70T/r/Q;UF?IBLZNZ4SxPRL(Ik_u,bK@uMhrMwM6^<"
      nonce_key: "w#)Y5<mlw).0@PB2j_hUyO^FWdSBYJ-a)?gxA)rd1y!x$3SsDt,lR^vkR(vWwY56"
      auth_salt: "Puq#)c8yc;jyK;lMeYg8:FtvN{{;f;D0pU?dHGI;,6s9D0J-pugpvBiocW6#Xs+." 
      secure_auth_salt: "D]NGAJ:N8lBt9O.Di!k.<))UZEEc<h$,7ooP?x!7#zzW<bJeD#pY|Ob.t@3z?;CS"
      logged_in_salt: "N!)BiMa{[+&!r}S+b{RH`j1<T(=Gd`92hYi+`fnvK3!=Bg3N`N|f4B1@<u5B_1)V"
      nonce_salt: ".Ba8OKzT-ol3Ak)]U&=qv03w^N!>y]OBsnlmH&5xT--1[tU#>G>^SIV:Fl|SSeqU"
